import { defineBoot } from "#q-app/wrappers";
import Modal from "src/components/Modal.vue";
import VPassword from "src/components/VPassword.vue";
import VCpf from "src/components/VCpf.vue";
import VCnpj from "src/components/VCnpj.vue";
import VTelefone from "src/components/VTelefone.vue";
import VCep from "src/components/VCep.vue";
import VStatusBadge from "src/components/VStatusBadge.vue";
import VEmptyState from "src/components/VEmptyState.vue";
import VAutocomplete from "src/components/VAutocomplete.vue";
import VSelectEstado from "src/components/VSelectEstado.vue";
import VSelectBanco from "src/components/VSelectBanco.vue";
import VOtp from "src/components/VOtp.vue";
import VQrcode from "src/components/VQrcode.vue";
import VUpload from "src/components/VUpload.vue";
import VLabel from "src/components/VLabel.vue";
import VAlert from "src/components/VAlert.vue";
import VDate from "src/components/VDate.vue";
import VMoney from "src/components/VMoney.vue";
import VConfirm from "src/components/VConfirm.vue";
import VDataTable from "src/components/VDataTable.vue";
import VForm from "src/components/VForm.vue";
import VSelectCidade from "src/components/VSelectCidade.vue";
import VEditor from "src/components/VEditor.vue";
import VPainel from "src/components/VPainel.vue";
import VPageHeader from "src/components/VPageHeader.vue";
import VStatCard from "src/components/VStatCard.vue";
import VAvatar from "src/components/VAvatar.vue";
import VCopy from "src/components/VCopy.vue";
import VTimeline from "src/components/VTimeline.vue";
import VFilter from "src/components/VFilter.vue";
import VChecklist from "src/components/VChecklist.vue";
import VSelect from "src/components/VSelect.vue";

export default defineBoot(async ({ app }) => {
  app.component("modal", Modal);
  app.component("v-password", VPassword);
  app.component("v-cpf", VCpf);
  app.component("v-cnpj", VCnpj);
  app.component("v-telefone", VTelefone);
  app.component("v-cep", VCep);
  app.component("v-status-badge", VStatusBadge);
  app.component("v-empty-state", VEmptyState);
  app.component("v-autocomplete", VAutocomplete);
  app.component("v-select-estado", VSelectEstado);
  app.component("v-select-banco", VSelectBanco);
  app.component("v-otp", VOtp);
  app.component("v-qrcode", VQrcode);
  app.component("v-upload", VUpload);
  app.component("v-label", VLabel);
  app.component("v-alert", VAlert);
  app.component("v-date", VDate);
  app.component("v-money", VMoney);
  app.component("v-confirm", VConfirm);
  app.component("v-data-table", VDataTable);
  app.component("v-form", VForm);
  app.component("v-select-cidade", VSelectCidade);
  app.component("v-editor", VEditor);
  app.component("v-painel", VPainel);
  app.component("v-page-header", VPageHeader);
  app.component("v-stat-card", VStatCard);
  app.component("v-avatar", VAvatar);
  app.component("v-copy", VCopy);
  app.component("v-timeline", VTimeline);
  app.component("v-filter", VFilter);
  app.component("v-checklist", VChecklist);
  app.component("v-select", VSelect);
});
